### ISSUE TITLE
[SIP-2] Update Need to Reserve Space on Every Upload to File Storage

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/filestorage#90]
# SKALE Improvement Proposal 2 | Remove Need for Reserve Space on Every File Upload
## The Problem 
* When uploading a file to SKALE FileStorage, space must be reserved every time. This results in extra smart contract calls every time and I higher possibility for error.

## A Solution
Allow the SKALE File Storage configuration to have a simple tracker that holds total space reserved. The total space reserved of all individuals can never exceed the total space available for the SKALE chain. Additionally, a user can reserve X amount of space and only utilize Y% of the space at any given time. This in itself I see as a problem, however, I believe it can be solved by allowing the FileStorage contract to be configured by the sChain owner to customize the abilities of the solution to the generated problem. This can be done by only allowing an individual to owner up to W amount at any given time, only allow a user to own Z percentage of the total file storage. Another example is having a starting block at at a value of B and then the FileStorage can only expand in increments of C. 

## Example:
The client application calls upload file to file storage contract. The file storage contract checks the user uploading the file and if the user has allocated, yet unused space; the file will upload successfully. If not, the user will be prompted to unlock additional storage according to the platform structure.

┆Issue is synchronized with this [Jira Task](https://skalelabs.atlassian.net/browse/SKALE-5045)

**Comment by cstrangedk** [comment]
Resolved by #80 and v2 release
